# Window configuration
[window]
dimensions = { columns = 80, lines = 24 }
opacity = 1.0

# Font configuration
[font]
size = 12

[font.normal]
family = "Terminess Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

# -----------------------------------------------------------------------------
# Monokai Pure Black Alacritty
# -----------------------------------------------------------------------------
[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.cursor]
text   = "#000000"
cursor = "#FFFFFF"

[colors.normal]
black   = "#000000"
red     = "#FF0000"
green   = "#00FF00"
yellow  = "#FFFF00"
blue    = "#0000FF"
magenta = "#FF00FF"
cyan    = "#00FFFF"
white   = "#FFFFFF"

[colors.bright]
black   = "#888888"
red     = "#FF5555"
green   = "#55FF55"
yellow  = "#FFFF55"
blue    = "#5555FF"
magenta = "#FF55FF"
cyan    = "#55FFFF"
white   = "#FFFFFF"

