# Window configuration
[window]
dimensions = { columns = 120, lines = 30 }
opacity = 0.95


# Font configuration
[font]
size = 14

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

# -----------------------------------------------------------------------------
# Monokai Pure Black Alacritty
# by jackmhny, adapted from https://app.unpkg.com/alacritty-themes@4.1.5/files/themes/Monokai.dark.yml
# -----------------------------------------------------------------------------

[colors.primary]
background = '#000000'
foreground = '#f8f8f2'

[colors.cursor]
cursor = '#f8f8f2'
text = '#000000'

# Normal colors
[colors.normal]
black = '#000000'
red = '#f92672'
green = '#a6e22e'
yellow = '#f4bf75'
blue = '#66d9ef'
magenta = '#ae81ff'
cyan = '#a1efe4'
white = '#f8f8f2'

# Bright colors
[colors.bright]
black = '#75715e'
red = '#f92672'
green = '#a6e22e'
yellow = '#f4bf75'
blue = '#66d9ef'
magenta = '#ae81ff'
cyan = '#a1efe4'
white = '#f9f8f5'

