Section "InputClass"
     Identifier "touchpad libinput defaults"
     MatchIsTouchpad "on"
     MatchDevicePath "/dev/input/event*"
     Driver "libinput"
     Option "NaturalScrolling" "true"
     Option "Tapping" "true"
EndSection
